### ISSUE TITLE
3D Touch

### ISSUE THREAD

**Issue by Urban225** [Mathildeuh/Wanhao-D12-230-Nano-s-V1.3#1]
Bonjour,

Je n'ai pas encore reçu ma D12 (d'ici demain) mais j'aurais surement la V1.3.

Déjà merci pour le firmware pour le BLTouch car je pensais que je ne pourrais pas l'utiliser du coup.

Tu pourrais me dire le pin quand tu parle de en haut à gauche ici : 

https://github.com/Mathildeuh/Wanhao-D12-230-Nano-s-V1.3/wiki/3D-BL-Touch

Si tu pouvais l'entourer car je le vois pas sur la photo ^^

Merci :)

**Comment by Mathildeuh** [comment]
Salut ! Le connecteur se trouve entre les 4 pins blancs et le pin vert tout en haut a gauche.

**Comment by YourSelft487** [comment]
Salut, @Mathildeuh il faudrais modifier l'image pour entourer le pin ainsi que le connecteur concerné.

**Comment by Mathildeuh** [comment]
> Salut, @Mathildeuh il faudrais modifier l'image pour entourer le pin ainsi que le connecteur concerné. 

Oui, je reprendrais une photo plus claire quand j'en aurais l'occasion.
